apiVersion: apps/v1
kind: Deployment
metadata:
  name: newrelic-hook-controller
  labels:
    app: newrelic-hook-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newrelic-hook-controller
  template:
    metadata:
      labels:
        app: newrelic-hook-controller
    spec:
      containers:
      - image: newrelic-hook-controller:latest # To be defined eventually
        imagePullPolicy: Always
        name: newrelic-hook-controller
