apiVersion: v1
kind: Service
metadata:
  name: newrelic-hook-controller
  labels:
    app: newrelic-hook-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: newrelic-hook-controller
  type: ClusterIP