apiVersion: v1
kind: Service
metadata:
  name: flux-newrelic
  labels:
    app: flux-newrelic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flux-newrelic
  type: ClusterIP